### ISSUE TITLE
Unable to un-minify source code

### ISSUE THREAD

**Issue by Wesleyzxc** [getsentry/sentry-javascript-bundler-plugins#292]
### Environment

What version are you running? Etc.
```
"@sentry/webpack-plugin": "^2.0.0",
"@sentry/react": "^7.28.0",
"@sentry/tracing": "^7.28.0",
```

### Steps to Reproduce

1. I'm currently using react-app-rewired, with the following config for `sentryWebpackPlugin`:
```    sentryWebpackPlugin({
      org: <org>,
      project: <proj>,
      authToken: process.env.SENTRY_AUTH_TOKEN,
      debug: false,
      sourcemaps: {
        assets: "./build/**",
        ignore: ["./node_modules/**"],
        ignoreFile: "./gitignore",
      },
      // Use the below option because SDK version is lower than 7.47.0:
      release: {
        name: process.env.npm_package_version,
        deploy: { env: process.env.REACT_APP_STAGE },
        uploadLegacySourcemaps: {
          // I notice in docs.sentry.io uses `include` here https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/webpack but it didn't look like a valid option in the npm docs https://www.npmjs.com/package/@sentry/webpack-plugin
          urlPrefix: "~/static/js", 
          paths: ["./src/**", "./build/**"],
          ext: [".js", ".jsx", ".ts", ".tsx"],
          ignore: ["node_modules", "**/node_modules/**", "./src/__mocks__", "**/__tests__/**", "**/__test__/**"],
        },
      },
    }),
```
2. Run `npm run build`
3. Source maps and source code gets uploaded to Sentry with a release version.
4. On build, source maps is uploaded to Sentry in 3 bundles:
My actual source code,
The build artifacts below:
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/36616095/8d593b18-4882-4308-a73b-7416143b67c9)
And a bundle with the debug id:
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/36616095/12995cee-bd13-4985-8834-41408d4543a2)
5. Run `serve -s build` and throw an error in the app

### Expected Result

In the sentry issue it should show where the error was.

### Actual Result

Sentry issue gives the following warning:
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/36616095/44620036-dc34-4fb6-b522-992a84030080)

**Comment by lforst** [comment]
Hey, I recommend you update the SDK and the bundler plugins to the newest version instead of using `uploadLegacySourcemaps` it will be much simpler thanresolving this.

**Comment by Wesleyzxc** [comment]
Cheers, I ended up updating to the latest versions and it worked with the plugin. Would appreciate if we have updated docs for both the legacy and current options to know what are the _primary_ options to focus on

**Comment by lforst** [comment]
@Wesleyzxc thanks for the feedback. :) This was a rather big undertaking - both in the plugin and in the Sentry backend - so we're just now in the process of adjusting the docs.

**Comment by 74io** [comment]
How will we know when there is some accurate information about this? 3 days later and still not managed to get sourcemaps to work. There is just so much conflicting information out there as folks seem to be opting for trial and error development. Great that it has all been re-written, but very frustrating that there is not a clear way to use it. It is a real show stopper.
